steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/k8s-deployment-407205/nodejs-restapi', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/k8s-deployment-407205/nodejs-restapi']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=k8s-configs/deployment.yaml'
      - '--image=gcr.io/k8s-deployment-407205/nodejs-restapi'
      - '--location=us-central1'
      - '--cluster=autopilot-cluster-1'


