steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/k8s-deployment/nodejs-restapi', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/k8s-deployment/nodejs-restapi']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/deployment.yaml']

images:
- 'gcr.io/k8s-deployment/nodejs-restapi'

