apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-service
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - name: nodejs-app
          image: gcr.io/k8s-deployment/restapi:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: restapi
spec:
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
