apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi  
  template:
    metadata:
      labels:
        app: restapi
        
    spec:
      containers:
        - name: nodejs-app
          image: gcr.io/k8s-deployment-407205/nodejs-restapi
          ports:
            - containerPort: 3001
          
---
apiVersion: v1
kind: Service
metadata:
  name: restapi
spec:
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 10256
      targetPort: 3001
  type: LoadBalancer
