---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi  
  template:
    metadata:
      labels:
        app: restapi  
    spec:
      containers:
        - name: nodejs-app
          image: gcr.io/k8s-deployment-407205/nodejs-restapi
          ports:
            - containerPort: 5000
          
---
apiVersion: v1
kind: Service
metadata:
  name: nodejssvc
spec:
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000
  type: LoadBalancer
